[workspace]
members = [
    "src/client",
    "src/service",
    "src/playground_kit",
]
resolver = "2"

[workspace.package]
name = "autonomic_playground"
version = "0.1.0"
edition = "2021"
description = "A playground for the Autonomic project"
license = "MIT"
readme = "README.md"
repository = "https://github.com/geo-mak/autonomic_playground"